#!/bin/sh

# -------------------------- VARIABLES
export pkg_ext='betopkg' # package extension
export version='1.0.0'

# disabling unicode support to get a better performance
export LC_ALL=C
export LANG=C

# -------------------------- FUNCTIONS
CHECK_PKG(){
    pkg_name="$@"

    # validating if package extension is 'betopkg'
    if ! echo "$pkg_name" | grep "\b${pkg_ext}\b$"; then
        printf '%s\n' "O formato do pacote deve ser: ${pkg_ext}"
        return 1
    fi

    # validating if there are spaces in package name
    if echo "$pkg_name" | grep -qE "[[:space:]]+"; then
        printf '%s\n' "Não use espaços no nome"
        printf '%s\n' "Abortando a criação"
        return 1
    fi

    # validating separators quantity in package name
    separators=$(echo "${pkg_name}" | grep -o "-" | wc -l)

    if [ "$separators" -lt '2' ] || [ "$separators" -gt '2' ]; then
        printf '%s\n' "Erro... O nome do pacote está com a quantidade inválida de separadores"
        printf '%s\n' "NomeDoPacote-Versao-Build.${pkg_ext}"
        return 1
    fi

    return 0

}

# creating package
CREATE_PKG() {
    pkg_name="$1" # get package name

      if [ "$VERBOSE" = "1" ]; then
        if tar -cvf ../${pkg_name} .; then
            printf '%s\n' "O pacote foi criado em ../${pkg_name}"
        else
            printf '%s\n' "O pacote ${pkg_name} não foi criado..."
            exit 1
        fi

    else
        if tar -cf ../${pkg_name} .; then
            printf '%s\n' "O pacote foi criado em ../${pkg_name}"
            return 0
        else
            printf '%s\n' "O pacote ${pkg_name} não foi criado..."
            exit 1
        fi
    fi

    return 0
}

USAGE(){
    cat <<EOF
createpkg - OPTIONS

    create, -c
        Create a package .betopkg. Only run if you are in main directory of project.
    verbose, -v

Author: Beto
Github: github.com/robertosamuelx
EOF
}

# if does not have any args, go to help
if [ -z "$1" ]; then
    USAGE
fi

# parser
while [ -n "$1" ]; do
    case "$1" in
        create|-c)
            CMD=$1
            shift
        ;;
        verbose|-v)
            VERBOSE=1 # 0 OFF / 1 ON
            shift
        ;;
        *.betopkg)
            PKG=$1
            shift
        ;;
        *)
            USAGE
             exit 1
        ;;
    esac
done

# -------------------------- START
case "$CMD" in
    create|-c)
        # package without name
        if [ -z "$CMD" ]; then
            printf '%s\n' "Você precisa fornecer um nome de pacote."
            exit 1
        fi

        CHECK_PKG "$PKG" || exit 1 # validade package name
        CREATE_PKG "$PKG" # calling function to create package
    ;;
esac